#!/usr/bin/bash

while getopts ":ht" opt; do
  case ${opt} in
    h )
      echo "Usage:"
      echo "    update          Update the docs and run all tests."
      echo "    update -h       Display this help message."
      echo "    update -t       Update the docs and the target of all tests."
      exit 0
      ;;
    t )
      echo "Updating the target of all tests."
      export TEST_RUN="init"
      ;;
    \? )
      echo "Invalid Option: -$OPTARG" 1>&2
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))


CURRPATH=`pwd`
SCRIPT=`realpath -s $0`
SCRIPTPATH=`dirname $SCRIPT`

cd $SCRIPTPATH

echo minifying brainsprite.js
minify brainsprite.js > brainsprite.min.js

echo updating js assets in brainsprite.py
cp brainsprite.min.js brainsprite/data/js/

echo python tests
pytest brainsprite/tests

echo flushing previous docs build
rm -rf $SCRIPTPATH/docs/build
rm -rf $SCRIPTPATH/docs/source/auto_examples
rm -rf $SCRIPTPATH/tests/plot_*.html

echo Building docs
cd docs
make html

echo Running tests and updating tutorial thumbnails
cd ..
npm test

export TEST_RUN="regular"

cd $CURRPATH
