"""
Anatomical scan viewer - html
=============================

This example generates a brainsprite viewer for an anatomical scan by filling an html template using python and tempita.
"""
#%%
# We first download an anatomical scan through one of nilearn's fetcher:
from nilearn import datasets

# one anatomical scan from the haxby dataset
haxby_dataset = datasets.fetch_haxby()
haxby_anat_filename = haxby_dataset.anat[0]

#%%
# Now let's have a look at a generic html template, and focus on the parts that need
# to be filled in:
#
# .. literalinclude:: ../_static/plot_anat_html_template.html
#    :language: html
#    :emphasize-lines: 5-8,12-15,22-25
#    :linenos:

#%%
# The parts with :code:`{{ }}` are part of the tempita language, and means that
# we need to populate these parts with brainsprite code. Let's use
# :code:`brainsprite_data` to generate the necessary html and js snippets.
# Note that the options we use here for the viewer are the same as for
# :code:`brainsprite_viewer` in the `plot_anat <plot_anat.html>`_ tutorial, and are
# explained in more details there.
from brainsprite import brainsprite_data

bsprite = brainsprite_data(haxby_anat_filename, cmap='gray',
                         symmetric_cmap=False, black_bg=True,
                         threshold=None, vmax=250, title="anatomical scan", value=False)
#%%
# We are going to need to inject the brainsprite.js library in the template.
# So we just load it in the session:
with open("../brainsprite.min.js") as f:
    bsprite["brainsprite_js"] = f.read()
    f.close()

#%%
# We can now open the template with tempita, and fill it with the required
# information:
import tempita
file_template = '../docs/source/_static/plot_anat_html_template.html'
tpl = tempita.Template.from_filename(file_template, encoding="utf-8")

viewer_html = tpl.substitute(
    bsprite_javascript=bsprite["brainsprite_js"],
    bsprite_html=bsprite["html"],
    bsprite_js=bsprite["js"]
)

#%%
# In order to save the html document, or insert it in a notebook, it is possible
# to use the :code:`HTMLDocument` class from nilearn. We'll also use the
# recommended size information for the viewer, which is generated by
# :code:`brainsprite_data`:
from nilearn.reporting import HTMLDocument
viewer = HTMLDocument(viewer_html, width=bsprite["size"][0], height=bsprite["size"][1])
viewer
#%%
# And the following instruction can be used to save the viewer in a stand-alone,
# html document:
viewer.save_as_html('plot_anat_html.html')
#%%
# That is the end of this tutorial, which actually largely explains how
# :code:`brainsprite_viewer` works internally. However, the templating approach
# presented here is generic, and allows to build complex html document featuring
# one or multiple brainsprite viewers, as demonstrated in other tutorials.
